In [ ]:
#NOTE : This notebook was run in google colab to speed up runnnig !

# Assignment 2

<i> Fetching Movie Data using API calls from TMDB website and perform text preprocessing on it : </i>
- Lowercasing each words ( lower()/regex )
- Remove html tags ( regex )
- Remove unwanted URL links ( regex )
- Remove Puctuation marks ( Maybe different if doing POS tagging )
- Removing / Converting emojis to a usable format ( emojis,regex )
- Removing Stopwords ( Irrelevant words which are used in sentence building( Not in POS tagging if done) )
- Convert Chat short forms into long form words
- Spelling correction ( Maybe caused by mistakenly )
- Tokenization
- Stemming or Lemmatization ( Suitable to the task )

problem description video :  https://youtu.be/6C0sLtw5ctc?si=echzGn7Spj0loKkC&t=3708

## Data fetching

> link : https://www.themoviedb.org/movie

# Flowchart :
[![](https://mermaid.ink/img/pako:eNqNVn9PIkkQ_SqV_mfvIogwoDDZeFlBVhfQjXKbyy17m3amgI4z05PuHhCN_-4HuI-4n-Squ0FGWJMjMc6P96pevapqeGKRjJGFbJrIZTTnysC4N1GTzP4BfT58nbDxqHcGN3wJPW64RvP-TtVO5QLVQuBywr5BtXoKZwS8xQQjA5tXEMmkSDNClCOeOXiX4JeZMIInLixcZjonspAbvMVu_nc9p06k7hyje0iF1iKbwYInBeoSY41suPAuIhh8MJBgNjPzfWBQAvLIFCTH4XNuDKpM74jv1h2tR6wbTKlQaLxo2ZT9Sk7D41_ug-395lnPPTqnkJsI36ME-a5v5w7WdxZwRVpRVRNcYAK5wlzJCJ2MHVbfs-pbwX_eDLXr4NyYXP8R1moT-twelFT3fZX9xpZ1MR4NwfCZp77_-s_pt4PTMsUX2rd-XkmV8kQ8IiznwqDOeYSOZhPpV4m8Hf2mHR6jRE594jFVUTOKi8S6ug1R5jU9r2XdkBnZRm2WQDOMKqIR3TWh5eAfLdo6C9fb4S3jPjrYBcG-kP6Yl6ZxA7nwEDeJMs25QpBKzERGg7PQUG5cCW6N_IJKTFeQEsDWJbTtmyYdGO8Tgi2h0DgtqMlFZsfTSgKFKRd7s-mpl3Zh5T1m4vFX-i89yOo_f8gpQ4qZgaUwc7gajgeuTUup4u_Gx8Dfft-N4IfjE0W4vnP6wWHhDud8IaTawX_ycJuRAifxOw0_f_wL7hoO4F15XdZYa1e90zzySHe1D7IWVRxAI_WBm7WOfaSdrsP_hbTzVK2-DX0NH9izI82lMpw87GEk9L7hAw-15fckXF2P4Y7mOk5Wtot2s0qNLQkaeJcH1orPpdanfAURV-plkH6Zbuj2Sea2k28JG3pkSdhakF4T_apPlUxpUkXKKWcuciT15VUceqFDf1ZwLbMQHBsScY-QSQM1yOicUqQ7A_qOyWb4hvi1JNvZIVmvQsDtjGKaCyUiniSrcnp_ggxtjz8kie-Wtqu4KaM6FQnFwnj9btcwf3CN7EIXStlMt4aSl3OsIWXayD26sqfd-V9jNzG3BtPUfSlpGNIlNezVCrIKmykRs9CoAissRTol7S17siEnzMwxpbQhXcZc3U_YJHsmTs6zv6VMNzQli9mchVOeaLorcjqlsCf4TPH05SlVEaPqyiIzLGwGLgYLn9gDCxv1k8NWuxM0G82jdtBqBa0KW7Gw2mgcHnc6ncbJ8VGnXQ_qx88V9ujS1g8b7WYQHJ0E7aBN7-v1CsNYGKlG_qeD-wXx_B_-S6DS?type=png)](https://mermaid.live/edit#pako:eNqNVn9v2kgQ_Sqj_ad3CoTYTghYVU5NCE0aSKqEq05XetXGHmAV22vtriE_lH_7Ae4j9pPc7C4EBxrpkBC2eW_mzZuZhSeWyBRZzCaZXCQzrgyMemM1Luwb6PXh65iNhr1juOYL6HHDNZr3t6p1JOeo5gIXY_YNms0jOCbgDWaYGFh9BYnMqrwgRD3isYOfEPy8EEbwzIWF80KXRBZyhbfY1eeJ5wREOplhcge50FoUU5jzrEJdYyyRoQvvIoLBewMZFlMz2wZGNSBPTEVyHL7kxqAq9Ib4k8DResS6xpwKhfBFy6rsV3JCj3-5j9b3q2c99-iUQq4ifE8y5Ju-nTpY31nAFWlF1cxwjhmUCkslE3QyNlh9zwrWgv-8HmjXwZkxpf4jbrXG9LrZqanu-yr74Zp1NhoOwPCpp77_-s_Rt52jOsUX2rd-XkqV80w8IixmwqAueYKOZhPpV4m8Hf19OzxGiZL6xFOqomUUF5l1dR2iztv3vAPrhizINmqzBJphVAmN6KYJBw7-0aKts3C1Ht467qODnRHsC-lPeW0aV5AzD3GTKPOSKwSpxFQUNDhzDfXG1eDWyC-oxOQBcgLYuoS2fdOkA9NtQrQmVBonFTW5Kux4WkmgMOdiazY99dwurLzDQjz-Sv-5B1n9p_clZcixMLAQZgaXg9GFa9NCqvS78THwt983I_jh-EQRrm6dfnBYuMUZnwupNvCfPNxmpMBZ-k7Dzx__gruGHXhXX5cl1toVdPf3PNJdbYOsRQ0H0Eh94GapYxtpp2v3fyHtPDWbb0Nfwy_s2ZGXUhlOHvYwEXrb8AsPteX3JFxejeCW5jrNHmwX7WbVGlsTdOFdvrBWfK61PucPkHClXgbpl-kGbp9kaTv5lrCBR9aELQXpJdGv-kTJnCZV5JxylqJEUl9fxYEXOvBnBdeyiMGxIRN3CIU00IKCzilFugug35hiim-IX0qynR2Q9SoGXM8o5qVQIuFZ9lBP70-Qge3xhyzz3dJ2FVdlNCcio1iYLr_bNMwfXEO70JVSNtONoeT1HEtInTZ0jy7taXf618hNzI3BPHc_ShoGdEkNe7WCrMGmSqQsNqrCBsuRTkl7y55syDEzM8wpbUyXKVd3YzYunolT8uJvKfMVTclqOmPxhGea7qqSTinsCT5VPH95SlWkqE5kVRgWR10Xg8VP7J7FYRDtHnS6UdjuHO6Fe-0obLAHFjfDYLfd7XajoBNEh-2w3X5usEeXNtgNO_tRtHcYdaJOeNgOggbDVBiphv6vg_sH8fwf_cygzw)

In [1]:
import requests
import pandas as pd

In [2]:
import os
TMDB_API_KEY = os.environ.get('TMDB_API_KEY')

In [146]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer,WordNetLemmatizer

nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

True

In [3]:
url = "https://api.themoviedb.org/3/movie/top_rated" # Link to the top rated movies of all time
params = {
    "api_key": TMDB_API_KEY, # The API_KEY hidden in colab secrets
    "language":"en-US", # The language we want the data in.
    "page":1 # Page no ( We are gonna iterate over this to get data from multiple pages )
}

In [4]:
returned_object = requests.get(url,params)

In [5]:
page1 = returned_object.json()

In [6]:
page1 # Our json object

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg',
   'genre_ids': [16, 28, 12, 14],
   'id': 980431,
   'title': 'Avatar Aang: The Last Airbender',
   'original_language': 'en',
   'original_title': 'Avatar Aang: The Last Airbender',
   'overview': "Avatar Aang, the world's last Airbender, learns of an ancient power that could save his culture from extinction. With the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve.",
   'popularity': 122.7143,
   'poster_path': '/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg',
   'release_date': '2026-07-24',
   'softcore': False,
   'video': False,
   'vote_average': 9.26,
   'vote_count': 851},
  {'adult': False,
   'backdrop_path': '/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg',
   'genre_ids': [35, 10749],
   'id': 1632181,
   'title': 'Accidental Partners',
   'original_language': 'es',
   'original_title': 'Socias por accidente',
   'overview': 'Two women discover they were both scammed by the same man (who also got them pregnant). They form an alliance to take revenge.',
   'popularity': 24.9711,
   'poster_path': '/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg',
   'release_date': '2026-03-12',
   'softcore': False,
   'video': False,
   'vote_average': 8.909,
   'vote_count': 350},
  {'adult': False,
   'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
   'genre_ids': [12, 16, 10751, 14],
   'id': 1007757,
   'title': 'Swapped',
   'original_language': 'en',
   'original_title': 'Swapped',
   'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
   'popularity': 51.2062,
   'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
   'release_date': '2026-05-01',
   'softcore': False,
   'video': False,
   'vote_average': 8.881,
   'vote_count': 2100},
  {'adult': False,
   'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'title': 'The Shawshank Redemption',
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
   'popularity': 56.9245,
   'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
   'release_date': '1994-09-23',
   'softcore': False,
   'video': False,
   'vote_average': 8.727,
   'vote_count': 31031},
  {'adult': False,
   'backdrop_path': '/1RgPyOhN4DRs225BGTlHJqCudII.jpg',
   'genre_ids': [16, 28, 14],
   'id': 1311031,
   'title': 'Demon Slayer: Kimetsu no Yaiba Infinity Castle',
   'original_language': 'ja',
   'original_title': '劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来',
   'overview': 'The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.',
   'popularity': 109.4062,
   'poster_path': '/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg',
   'release_date': '2025-07-18',
   'softcore': False,
   'video': False,
   'vote_average': 8.712,
   'vote_count': 1833},
  {'adult': False,
   'backdrop_path': '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'title': 'The Godfather',
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 59.0628,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'softcore': False,
   'video': False,
   'vote_average': 8.7,
   'vote_count': 23345},
  {'adult': False,
   'backdrop_path': '/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg',
   'genre_ids': [10402, 18],
   'id': 936075,
   'title': 'Michael',
   'original_language': 'en',
   'original_title': 'Michael',
   'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
   'popularity': 84.8355,
   'poster_path': '/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg',
   'release_date': '2026-04-22',
   'softcore': False,
   'video': False,
   'vote_average': 8.681,
   'vote_count': 4020},
  {'adult': False,
   'backdrop_path': '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
   'genre_ids': [878, 12],
   'id': 687163,
   'title': 'Project Hail Mary',
   'original_language': 'en',
   'original_title': 'Project Hail Mary',
   'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
   'popularity': 131.1924,
   'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
   'release_date': '2026-03-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.654,
   'vote_count': 7055},
  {'adult': False,
   'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
   'genre_ids': [18, 80],
   'id': 240,
   'title': 'The Godfather Part II',
   'original_language': 'en',
   'original_title': 'The Godfather Part II',
   'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
   'popularity': 31.3571,
   'poster_path': '/sSuQTCZwqKrNBNIsksO9IAUoWP9.jpg',
   'release_date': '1974-12-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.571,
   'vote_count': 14174},
  {'adult': False,
   'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
   'genre_ids': [18, 36, 10752],
   'id': 424,
   'title': "Schindler's List",
   'original_language': 'en',
   'original_title': "Schindler's List",
   'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
   'popularity': 34.1502,
   'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
   'release_date': '1993-12-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.57,
   'vote_count': 17738},
  {'adult': False,
   'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
   'genre_ids': [18],
   'id': 389,
   'title': '12 Angry Men',
   'original_language': 'en',
   'original_title': '12 Angry Men',
   'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
   'popularity': 27.3154,
   'poster_path': '/ppd84D2i9W8jXmsyInGyihiSyqz.jpg',
   'release_date': '1957-04-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.568,
   'vote_count': 10231},
  {'adult': False,
   'backdrop_path': '/3HaqAPZ0C8n6Hd5T86U53yJlBAN.jpg',
   'genre_ids': [18, 10749],
   'id': 1232449,
   'title': 'Young Hearts',
   'original_language': 'nl',
   'original_title': 'Young Hearts',
   'overview': '14-year-old Elias increasingly feels like an outsider in his village. When he meets his new neighbour of the same age, Alexander, Elias is confronted with his burgeoning sexuality.',
   'popularity': 18.1933,
   'poster_path': '/iGCtYxfuvXfy0BD5m6p7vKuPOxS.jpg',
   'release_date': '2024-10-26',
   'softcore': False,
   'video': False,
   'vote_average': 8.567,
   'vote_count': 304},
  {'adult': False,
   'backdrop_path': '/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg',
   'genre_ids': [28, 80, 53],
   'id': 155,
   'title': 'The Dark Knight',
   'original_language': 'en',
   'original_title': 'The Dark Knight',
   'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
   'popularity': 62.3278,
   'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
   'release_date': '2008-07-16',
   'softcore': False,
   'video': False,
   'vote_average': 8.534,
   'vote_count': 36390},
  {'adult': False,
   'backdrop_path': '/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg',
   'genre_ids': [16, 10751, 14],
   'id': 129,
   'title': 'Spirited Away',
   'original_language': 'ja',
   'original_title': '千と千尋の神隠し',
   'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
   'popularity': 35.3381,
   'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
   'release_date': '2001-07-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.534,
   'vote_count': 18690},
  {'adult': False,
   'backdrop_path': '/fr7F7156W8A5lSvrqHwNjtyrmLG.jpg',
   'genre_ids': [16, 28, 10749, 14],
   'id': 1218925,
   'title': 'Chainsaw Man - The Movie: Reze Arc',
   'original_language': 'ja',
   'original_title': '劇場版 チェンソーマン レゼ篇',
   'overview': "In a brutal war between devils, hunters, and secret enemies, a mysterious girl named Reze has stepped into Denji's world, and he faces his deadliest battle yet, fueled by love in a world where survival knows no rules.",
   'popularity': 34.5511,
   'poster_path': '/crBfxNvvsQV3rATX12EuX4W9ECo.jpg',
   'release_date': '2025-09-19',
   'softcore': False,
   'video': False,
   'vote_average': 8.525,
   'vote_count': 1114},
  {'adult': False,
   'backdrop_path': '/amZavErrjrdgDwhsIdpWxHNenIx.jpg',
   'genre_ids': [14, 18, 80],
   'id': 497,
   'title': 'The Green Mile',
   'original_language': 'en',
   'original_title': 'The Green Mile',
   'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
   'popularity': 34.2412,
   'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
   'release_date': '1999-12-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.506,
   'vote_count': 19608},
  {'adult': False,
   'backdrop_path': '/84beTJf26mfhoasUlKSOiNSutyS.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 19404,
   'title': 'Dilwale Dulhania Le Jayenge',
   'original_language': 'hi',
   'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
   'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
   'popularity': 14.3904,
   'poster_path': '/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg',
   'release_date': '1995-10-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.505,
   'vote_count': 4613},
  {'adult': False,
   'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
   'genre_ids': [12, 14, 28],
   'id': 122,
   'title': 'The Lord of the Rings: The Return of the King',
   'original_language': 'en',
   'original_title': 'The Lord of the Rings: The Return of the King',
   'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
   'popularity': 50.4122,
   'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
   'release_date': '2003-12-17',
   'softcore': False,
   'video': False,
   'vote_average': 8.504,
   'vote_count': 27084},
  {'adult': False,
   'backdrop_path': '/vbC0rzdrb7Ohc2TkbEbxtOABECe.jpg',
   'genre_ids': [35, 53, 18],
   'id': 496243,
   'title': 'Parasite',
   'original_language': 'ko',
   'original_title': '기생충',
   'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
   'popularity': 37.1941,
   'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
   'release_date': '2019-05-30',
   'softcore': False,
   'video': False,
   'vote_average': 8.49,
   'vote_count': 21083},
  {'adult': False,
   'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg',
   'genre_ids': [16, 10749, 18],
   'id': 372058,
   'title': 'Your Name.',
   'original_language': 'ja',
   'original_title': '君の名は。',
   'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
   'popularity': 27.715,
   'poster_path': '/vfJFJPepRKapMd5G2ro7klIRysq.jpg',
   'release_date': '2016-07-01',
   'softcore': False,
   'video': False,
   'vote_average': 8.484,
   'vote_count': 12845}],
 'total_pages': 556,
 'total_results': 11112}

In [7]:
page1['page']

1

In [8]:
page1['total_pages']

556

In [9]:
page1['results'][0] # Every movie data is stored in this results list

{'adult': False,
 'backdrop_path': '/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg',
 'genre_ids': [16, 28, 12, 14],
 'id': 980431,
 'title': 'Avatar Aang: The Last Airbender',
 'original_language': 'en',
 'original_title': 'Avatar Aang: The Last Airbender',
 'overview': "Avatar Aang, the world's last Airbender, learns of an ancient power that could save his culture from extinction. With the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve.",
 'popularity': 122.7143,
 'poster_path': '/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg',
 'release_date': '2026-07-24',
 'softcore': False,
 'video': False,
 'vote_average': 9.26,
 'vote_count': 851}

In [10]:
len(page1['results']) # The max amount of movies in each page

20

In [11]:
# Now lets convert these into a dataframe
page1_df = pd.DataFrame(page1.get("results"))

In [12]:
page1_df.head(3)

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg,"[16, 28, 12, 14]",980431,Avatar Aang: The Last Airbender,en,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",122.7143,/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg,2026-07-24,False,False,9.260,851
1,False,/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg,"[35, 10749]",1632181,Accidental Partners,es,Socias por accidente,Two women discover they were both scammed by t...,24.9711,/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg,2026-03-12,False,False,8.909,350
2,False,/zMwhWailP1WY7sb6AoE6b8ugoy.jpg,"[12, 16, 10751, 14]",1007757,Swapped,en,Swapped,"A small woodland creature and a majestic bird,...",51.2062,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,2026-05-01,False,False,8.881,2100

In [13]:
# Now let's automate this process and try to get a large number of json in a iteration.
def fetch_json_movies(url,params):
  movies = []
  first_page = 1
  max_pages = 1
  try:
      params['page']=first_page
      response = requests.get(url,params=params)

      response.raise_for_status() # This triggers HTTPError if the response is not 200-299

      fetched_movies = response.json()

      max_pages = fetched_movies['total_pages']

      movies.extend(fetched_movies['results'])

  except requests.exceptions.HTTPError as err:
    print(f"Caught an error before sending request: {err}")
    return movies
  except requests.exceptions.RequestException as net_err:
    print(f"Page {first_page}: Network/Timeout error occurred: {net_err}")
    return movies

  for i in range(first_page+1,max_pages+1): # Temporary for now
    params["page"] = i
    try:
      response = requests.get(url,params=params)

      response.raise_for_status() # This triggers HTTPError if the response is not 200-299

      fetched_movies = response.json()
      movies.extend(fetched_movies['results'])

    except requests.exceptions.HTTPError as err:
      print(f"Page {i}: Bad status code received: {err}")
      break
    except requests.exceptions.RequestException as net_err:
      print(f"Page {i}: Network/Timeout error occurred: {net_err}")
      break
  return movies

In [14]:
# Set url and parameters
url = "https://api.themoviedb.org/3/movie/top_rated"
params = {
    "api_key": TMDB_API_KEY, # The API_KEY hidden in colab secrets
    "language":"en-US",
    "page":1 # Dummy for now , replace by the iterator in loop
}
all_movies = fetch_json_movies(url,params)

Page 501: Bad status code received: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=501

In [15]:
all_movies # The complete json

[{'adult': False,
  'backdrop_path': '/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg',
  'genre_ids': [16, 28, 12, 14],
  'id': 980431,
  'title': 'Avatar Aang: The Last Airbender',
  'original_language': 'en',
  'original_title': 'Avatar Aang: The Last Airbender',
  'overview': "Avatar Aang, the world's last Airbender, learns of an ancient power that could save his culture from extinction. With the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve.",
  'popularity': 122.7143,
  'poster_path': '/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg',
  'release_date': '2026-07-24',
  'softcore': False,
  'video': False,
  'vote_average': 9.26,
  'vote_count': 851},
 {'adult': False,
  'backdrop_path': '/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg',
  'genre_ids': [35, 10749],
  'id': 1632181,
  'title': 'Accidental Partners',
  'original_language': 'es',
  'original_title': 'Socias por accidente',
  'overview': 'Two women discover they were both scammed by the same man (who also got them pregnant). They form an alliance to take revenge.',
  'popularity': 24.9711,
  'poster_path': '/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg',
  'release_date': '2026-03-12',
  'softcore': False,
  'video': False,
  'vote_average': 8.909,
  'vote_count': 350},
 {'adult': False,
  'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
  'genre_ids': [12, 16, 10751, 14],
  'id': 1007757,
  'title': 'Swapped',
  'original_language': 'en',
  'original_title': 'Swapped',
  'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
  'popularity': 51.2062,
  'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
  'release_date': '2026-05-01',
  'softcore': False,
  'video': False,
  'vote_average': 8.881,
  'vote_count': 2100},
 {'adult': False,
  'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
  'genre_ids': [18, 80],
  'id': 278,
  'title': 'The Shawshank Redemption',
  'original_language': 'en',
  'original_title': 'The Shawshank Redemption',
  'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
  'popularity': 56.9245,
  'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
  'release_date': '1994-09-23',
  'softcore': False,
  'video': False,
  'vote_average': 8.727,
  'vote_count': 31031},
 {'adult': False,
  'backdrop_path': '/1RgPyOhN4DRs225BGTlHJqCudII.jpg',
  'genre_ids': [16, 28, 14],
  'id': 1311031,
  'title': 'Demon Slayer: Kimetsu no Yaiba Infinity Castle',
  'original_language': 'ja',
  'original_title': '劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来',
  'overview': 'The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.',
  'popularity': 109.4062,
  'poster_path': '/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg',
  'release_date': '2025-07-18',
  'softcore': False,
  'video': False,
  'vote_average': 8.712,
  'vote_count': 1833},
 {'adult': False,
  'backdrop_path': '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg',
  'genre_ids': [18, 80],
  'id': 238,
  'title': 'The Godfather',
  'original_language': 'en',
  'original_title': 'The Godfather',
  'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
  'popularity': 59.0628,
  'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
  'release_date': '1972-03-14',
  'softcore': False,
  'video': False,
  'vote_average': 8.7,
  'vote_count': 23345},
 {'adult': False,
  'backdrop_path': '/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg',
  'genre_ids': [10402, 18],
  'id': 936075,
  'title': 'Michael',
  'original_language': 'en',
  'original_title': 'Michael',
  'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
  'popularity': 84.8355,
  'poster_path': '/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg',
  'release_date': '2026-04-22',
  'softcore': False,
  'video': False,
  'vote_average': 8.681,
  'vote_count': 4020},
 {'adult': False,
  'backdrop_path': '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
  'genre_ids': [878, 12],
  'id': 687163,
  'title': 'Project Hail Mary',
  'original_language': 'en',
  'original_title': 'Project Hail Mary',
  'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
  'popularity': 131.1924,
  'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
  'release_date': '2026-03-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.654,
  'vote_count': 7055},
 {'adult': False,
  'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
  'genre_ids': [18, 80],
  'id': 240,
  'title': 'The Godfather Part II',
  'original_language': 'en',
  'original_title': 'The Godfather Part II',
  'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
  'popularity': 31.3571,
  'poster_path': '/sSuQTCZwqKrNBNIsksO9IAUoWP9.jpg',
  'release_date': '1974-12-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.571,
  'vote_count': 14174},
 {'adult': False,
  'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
  'genre_ids': [18, 36, 10752],
  'id': 424,
  'title': "Schindler's List",
  'original_language': 'en',
  'original_title': "Schindler's List",
  'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
  'popularity': 34.1502,
  'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
  'release_date': '1993-12-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.57,
  'vote_count': 17738},
 {'adult': False,
  'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
  'genre_ids': [18],
  'id': 389,
  'title': '12 Angry Men',
  'original_language': 'en',
  'original_title': '12 Angry Men',
  'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
  'popularity': 27.3154,
  'poster_path': '/ppd84D2i9W8jXmsyInGyihiSyqz.jpg',
  'release_date': '1957-04-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.568,
  'vote_count': 10231},
 {'adult': False,
  'backdrop_path': '/3HaqAPZ0C8n6Hd5T86U53yJlBAN.jpg',
  'genre_ids': [18, 10749],
  'id': 1232449,
  'title': 'Young Hearts',
  'original_language': 'nl',
  'original_title': 'Young Hearts',
  'overview': '14-year-old Elias increasingly feels like an outsider in his village. When he meets his new neighbour of the same age, Alexander, Elias is confronted with his burgeoning sexuality.',
  'popularity': 18.1933,
  'poster_path': '/iGCtYxfuvXfy0BD5m6p7vKuPOxS.jpg',
  'release_date': '2024-10-26',
  'softcore': False,
  'video': False,
  'vote_average': 8.567,
  'vote_count': 304},
 {'adult': False,
  'backdrop_path': '/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg',
  'genre_ids': [28, 80, 53],
  'id': 155,
  'title': 'The Dark Knight',
  'original_language': 'en',
  'original_title': 'The Dark Knight',
  'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
  'popularity': 62.3278,
  'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
  'release_date': '2008-07-16',
  'softcore': False,
  'video': False,
  'vote_average': 8.534,
  'vote_count': 36390},
 {'adult': False,
  'backdrop_path': '/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg',
  'genre_ids': [16, 10751, 14],
  'id': 129,
  'title': 'Spirited Away',
  'original_language': 'ja',
  'original_title': '千と千尋の神隠し',
  'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
  'popularity': 35.3381,
  'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
  'release_date': '2001-07-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.534,
  'vote_count': 18690},
 {'adult': False,
  'backdrop_path': '/fr7F7156W8A5lSvrqHwNjtyrmLG.jpg',
  'genre_ids': [16, 28, 10749, 14],
  'id': 1218925,
  'title': 'Chainsaw Man - The Movie: Reze Arc',
  'original_language': 'ja',
  'original_title': '劇場版 チェンソーマン レゼ篇',
  'overview': "In a brutal war between devils, hunters, and secret enemies, a mysterious girl named Reze has stepped into Denji's world, and he faces his deadliest battle yet, fueled by love in a world where survival knows no rules.",
  'popularity': 34.5511,
  'poster_path': '/crBfxNvvsQV3rATX12EuX4W9ECo.jpg',
  'release_date': '2025-09-19',
  'softcore': False,
  'video': False,
  'vote_average': 8.525,
  'vote_count': 1114},
 {'adult': False,
  'backdrop_path': '/amZavErrjrdgDwhsIdpWxHNenIx.jpg',
  'genre_ids': [14, 18, 80],
  'id': 497,
  'title': 'The Green Mile',
  'original_language': 'en',
  'original_title': 'The Green Mile',
  'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
  'popularity': 34.2412,
  'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
  'release_date': '1999-12-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.506,
  'vote_count': 19608},
 {'adult': False,
  'backdrop_path': '/84beTJf26mfhoasUlKSOiNSutyS.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 19404,
  'title': 'Dilwale Dulhania Le Jayenge',
  'original_language': 'hi',
  'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
  'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
  'popularity': 14.3904,
  'poster_path': '/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg',
  'release_date': '1995-10-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.505,
  'vote_count': 4613},
 {'adult': False,
  'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
  'genre_ids': [12, 14, 28],
  'id': 122,
  'title': 'The Lord of the Rings: The Return of the King',
  'original_language': 'en',
  'original_title': 'The Lord of the Rings: The Return of the King',
  'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
  'popularity': 50.4122,
  'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
  'release_date': '2003-12-17',
  'softcore': False,
  'video': False,
  'vote_average': 8.504,
  'vote_count': 27084},
 {'adult': False,
  'backdrop_path': '/vbC0rzdrb7Ohc2TkbEbxtOABECe.jpg',
  'genre_ids': [35, 53, 18],
  'id': 496243,
  'title': 'Parasite',
  'original_language': 'ko',
  'original_title': '기생충',
  'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
  'popularity': 37.1941,
  'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
  'release_date': '2019-05-30',
  'softcore': False,
  'video': False,
  'vote_average': 8.49,
  'vote_count': 21083},
 {'adult': False,
  'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg',
  'genre_ids': [16, 10749, 18],
  'id': 372058,
  'title': 'Your Name.',
  'original_language': 'ja',
  'original_title': '君の名は。',
  'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
  'popularity': 27.715,
  'poster_path': '/vfJFJPepRKapMd5G2ro7klIRysq.jpg',
  'release_date': '2016-07-01',
  'softcore': False,
  'video': False,
  'vote_average': 8.484,
  'vote_count': 12845},
 {'adult': False,
  'backdrop_path': '/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg',
  'genre_ids': [12, 18, 878],
  'id': 157336,
  'title': 'Interstellar',
  'original_language': 'en',
  'original_title': 'Interstellar',
  'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
  'popularity': 67.7987,
  'poster_path': '/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg',
  'release_date': '2014-11-05',
  'softcore': False,
  'video': False,
  'vote_average': 8.484,
  'vote_count': 40754},
 {'adult': False,
  'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
  'genre_ids': [53, 80, 35],
  'id': 680,
  'title': 'Pulp Fiction',
  'original_language': 'en',
  'original_title': 'Pulp Fiction',
  'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
  'popularity': 41.3649,
  'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
  'release_date': '1994-09-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.481,
  'vote_count': 30636},
 {'adult': False,
  'backdrop_path': '/bVGHSe47W6oCQL1Q88pvRAet51A.jpg',
  'genre_ids': [18, 9648],
  'id': 1330021,
  'title': 'Remarkably Bright Creatures',
  'original_language': 'en',
  'original_title': 'Remarkably Bright Creatures',
  'overview': 'Through unlikely bonds formed during night shifts at a local aquarium, Tova, an elderly widow, learns of a life-changing discovery that may bring her joy and wonder once again.',
  'popularity': 17.4217,
  'poster_path': '/9HcEqn3D4J6b2Z0jK54id9nA0fr.jpg',
  'release_date': '2026-05-07',
  'softcore': False,
  'video': False,
  'vote_average': 8.478,
  'vote_count': 831},
 {'adult': False,
  'backdrop_path': '/x4biAVdPVCghBlsVIzB6NmbghIz.jpg',
  'genre_ids': [37],
  'id': 429,
  'title': 'The Good, the Bad and the Ugly',
  'original_language': 'it',
  'original_title': 'Il buono, il brutto, il cattivo',
  'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
  'popularity': 24.302,
  'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
  'release_date': '1966-12-23',
  'softcore': False,
  'video': False,
  'vote_average': 8.466,
  'vote_count': 9841},
 {'adult': False,
  'backdrop_path': '/66Kn4XWhkuPkJxOJyPEx4U2CUfN.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 13,
  'title': 'Forrest Gump',
  'original_language': 'en',
  'original_title': 'Forrest Gump',
  'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
  'popularity': 35.229,
  'poster_path': '/Cw4hIUIAmSYfK9QfaUW5igp9La.jpg',
  'release_date': '1994-06-23',
  'softcore': False,
  'video': False,
  'vote_average': 8.463,
  'vote_count': 30203},
 {'adult': False,
  'backdrop_path': '/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg',
  'genre_ids': [35, 10749],
  'id': 1181678,
  'title': '¿Quieres ser mi hijo?',
  'original_language': 'en',
  'original_title': '¿Quieres ser mi hijo?',
  'overview': 'Lu, a conformist woman in her forties, learns that her 15-year partner has been having extramarital affairs. Starting from scratch, she gets involved in an unexpected relationship with a young womanizer.',
  'popularity': 7.2598,
  'poster_path': '/6PQJsmuvSMZQMmlJfTpjIkrizUh.jpg',
  'release_date': '2023-09-21',
  'softcore': False,
  'video': False,
  'vote_average': 8.461,
  'vote_count': 363},
 {'adult': False,
  'backdrop_path': '/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg',
  'genre_ids': [28, 18],
  'id': 346,
  'title': 'Seven Samurai',
  'original_language': 'ja',
  'original_title': '七人の侍',
  'overview': "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
  'popularity': 15.0583,
  'poster_path': '/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg',
  'release_date': '1954-04-26',
  'softcore': False,
  'video': False,
  'vote_average': 8.451,
  'vote_count': 4312},
 {'adult': False,
  'backdrop_path': '/nC3IjYhUgZWgfKfFX0ygMigFwgc.jpg',
  'genre_ids': [28, 18, 36],
  'id': 14537,
  'title': 'Harakiri',
  'original_language': 'ja',
  'original_title': '切腹',
  'overview': 'Down-on-his-luck veteran Tsugumo Hanshirō enters the courtyard of the prosperous House of Iyi. Unemployed, and with no family, he hopes to find a place to commit seppuku—and a worthy second to deliver the coup de grâce in his suicide ritual. The senior counselor for the Iyi clan questions the ronin’s resolve and integrity, suspecting Hanshirō of seeking charity rather than an honorable end. What follows is a pair of interlocking stories which lay bare the difference between honor and respect, and promises to examine the legendary foundations of the Samurai code.',
  'popularity': 11.6436,
  'poster_path': '/zK7HsOC7QxW1ldKIeFG8YJ5F2Eb.jpg',
  'release_date': '1962-09-15',

In [16]:
# I could have also converted this to a pandas DataFrame but I would like to do it outside the function for cleanliness
movies = pd.DataFrame(all_movies)

In [17]:
movies

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg,"[16, 28, 12, 14]",980431,Avatar Aang: The Last Airbender,en,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",122.7143,/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg,2026-07-24,False,False,9.260,851
1,False,/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg,"[35, 10749]",1632181,Accidental Partners,es,Socias por accidente,Two women discover they were both scammed by t...,24.9711,/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg,2026-03-12,False,False,8.909,350
2,False,/zMwhWailP1WY7sb6AoE6b8ugoy.jpg,"[12, 16, 10751, 14]",1007757,Swapped,en,Swapped,"A small woodland creature and a majestic bird,...",51.2062,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,2026-05-01,False,False,8.881,2100
3,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,The Shawshank Redemption,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,56.9245,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,False,False,8.727,31031
4,False,/1RgPyOhN4DRs225BGTlHJqCudII.jpg,"[16, 28, 14]",1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,ja,劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来,The Demon Slayer Corps are drawn into the Infi...,109.4062,/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg,2025-07-18,False,False,8.712,1833
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,/aXBcJsY4amhsT0UxIjLiVqFbSuM.jpg,"[18, 53]",340584,Lavender,en,Lavender,A photographer struggling with memory loss dis...,1.6955,/tAPvkv0XTeLFqlvMgtlFB8mqk3L.jpg,2016-11-04,False,False,5.639,360
9996,False,/mUWjBk12lY0om9iEFK8wdhxj7It.jpg,"[35, 53, 27]",101519,A Fantastic Fear of Everything,en,A Fantastic Fear of Everything,Jack is a children's author turned crime novel...,1.8728,/sMZyKSo8b47VW1h2zjjGUZIefV1.jpg,2012-06-07,False,False,5.639,319
9997,False,/qSx994cBgJ2jgc5Gx4hc3QjtJP0.jpg,[35],8277,American Pie Presents: Beta House,en,American Pie Presents: Beta House,"Erik, Ryan, and Cooze start college and pledge...",8.1732,/j7eGbwVb9hTaRFWMlSa7C1OYp3T.jpg,2007-12-06,False,False,5.639,2059
9998,False,/uTqxyztRGHSq96JYhByyNFuqqld.jpg,"[878, 28, 53]",8202,Æon Flux,en,Æon Flux,"400 years into the future, disease has wiped o...",7.1206,/5958Nt4QX6aRSUdQnvNw8wqjTJQ.jpg,2005-11-30,False,False,5.639,2504
9999,False,/kjVhc1Ba9dFhgsdzQLGKrUbfe1q.jpg,"[53, 878]",22825,The Box,en,The Box,"Norma and Arthur Lewis, a suburban couple with...",5.3030,/xMAmOu6xl4CsstixcuecBle9krd.jpg,2009-10-29,False,False,5.600,1925

In [18]:
# Now there is another mappig endpoint we have to fetch :
import requests
import pandas as pd

# 1. Set up the exact URL and parameters (Remove page since it isn't needed here)
url = "https://api.themoviedb.org/3/genre/movie/list"
params = {
    "api_key": TMDB_API_KEY,
    "language": "en-US"
}

def fetch_genres(url, params):
    try:
        response = requests.get(url, params=params, timeout=10)
        response.raise_for_status()

        data = response.json()

        # Safely extract the 'genres' list (default to empty list if missing)
        return data.get('genres', [])

    except requests.exceptions.RequestException as err:
        print(f"Failed to fetch genres: {err}")
        return []

# 2. Fetch the data using the clean function
all_genres = fetch_genres(url, params)

# 3. Convert directly to a beautiful Pandas DataFrame
genres = pd.DataFrame(all_genres)

In [19]:
genres.shape

(19, 2)

In [20]:
# Now we have both the datasets successfully

In [21]:
# Now let's map the genres to the numeri value

In [22]:
genres

       id             name
0      28           Action
1      12        Adventure
2      16        Animation
3      35           Comedy
4      80            Crime
5      99      Documentary
6      18            Drama
7   10751           Family
8      14          Fantasy
9      36          History
10     27           Horror
11  10402            Music
12   9648          Mystery
13  10749          Romance
14    878  Science Fiction
15  10770         TV Movie
16     53         Thriller
17  10752              War
18     37          Western

In [23]:
movies.head()

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg,"[16, 28, 12, 14]",980431,Avatar Aang: The Last Airbender,en,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",122.7143,/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg,2026-07-24,False,False,9.260,851
1,False,/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg,"[35, 10749]",1632181,Accidental Partners,es,Socias por accidente,Two women discover they were both scammed by t...,24.9711,/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg,2026-03-12,False,False,8.909,350
2,False,/zMwhWailP1WY7sb6AoE6b8ugoy.jpg,"[12, 16, 10751, 14]",1007757,Swapped,en,Swapped,"A small woodland creature and a majestic bird,...",51.2062,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,2026-05-01,False,False,8.881,2100
3,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,The Shawshank Redemption,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,56.9245,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,False,False,8.727,31031
4,False,/1RgPyOhN4DRs225BGTlHJqCudII.jpg,"[16, 28, 14]",1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,ja,劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来,The Demon Slayer Corps are drawn into the Infi...,109.4062,/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg,2025-07-18,False,False,8.712,1833

In [24]:
# Turn the genres DataFrame into a clean ID-to-Name map
genre_map = genres.set_index('id')['name'].to_dict()

In [25]:
genre_map

{28: 'Action',
 12: 'Adventure',
 16: 'Animation',
 35: 'Comedy',
 80: 'Crime',
 99: 'Documentary',
 18: 'Drama',
 10751: 'Family',
 14: 'Fantasy',
 36: 'History',
 27: 'Horror',
 10402: 'Music',
 9648: 'Mystery',
 10749: 'Romance',
 878: 'Science Fiction',
 10770: 'TV Movie',
 53: 'Thriller',
 10752: 'War',
 37: 'Western'}

In [26]:
#  Use your new map to convert numeric IDs to real names in your movies table
movies['genre_names'] = movies['genre_ids'].apply(
    lambda ids: [genre_map[id_num] for id_num in ids if id_num in genre_map]
)

In [27]:
movies[['title', 'genre_ids', 'genre_names']].head() # Done mapping successfully

,title,genre_ids,genre_names
0,Avatar Aang: The Last Airbender,"[16, 28, 12, 14]","[Animation, Action, Adventure, Fantasy]"
1,Accidental Partners,"[35, 10749]","[Comedy, Romance]"
2,Swapped,"[12, 16, 10751, 14]","[Adventure, Animation, Family, Fantasy]"
3,The Shawshank Redemption,"[18, 80]","[Drama, Crime]"
4,Demon Slayer: Kimetsu no Yaiba Infinity Castle,"[16, 28, 14]","[Animation, Action, Fantasy]"

In [28]:
# Now we will first decide which features to choose and which one to not for this task

In [29]:
movies.sample(3)

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count,genre_names
1014,False,/en971MEXui9diirXlogOrPKmsEn.jpg,"[28, 12, 35]",293660,Deadpool,en,Deadpool,The origin story of former Special Forces oper...,30.3931,/3E53WEZJqP6aM84D8CckXx4pIHw.jpg,2016-02-09,False,False,7.625,33096,"[Action, Adventure, Comedy]"
1775,False,/dLhBHSv5v2wKuZQ3sumthfLplHU.jpg,"[878, 28, 18]",364433,They Call Me Jeeg,it,Lo chiamavano Jeeg Robot,"Exposed to radioactive waste, small-time crook...",3.6607,/zvJPbyWflWHbHMHSdue1n4N69tC.jpg,2016-02-25,False,False,7.398,2599,"[Science Fiction, Action, Drama]"
8263,False,/oMaj75G2WFw66xI1TREg1hrToSg.jpg,"[28, 14, 878, 12]",268896,Pacific Rim: Uprising,en,Pacific Rim: Uprising,It has been ten years since The Battle of the ...,10.8019,/nFWhttU8PM50t25NPdy7PE7rv3G.jpg,2018-03-21,False,False,6.126,5441,"[Action, Fantasy, Science Fiction, Adventure]"

### The subset of columns to select for our problem :

- title
- overview
- genre_names

In [30]:
df = movies[['title','overview','genre_names']]

In [31]:
df.head()

,title,overview,genre_names
0,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...","[Animation, Action, Adventure, Fantasy]"
1,Accidental Partners,Two women discover they were both scammed by t...,"[Comedy, Romance]"
2,Swapped,"A small woodland creature and a majestic bird,...","[Adventure, Animation, Family, Fantasy]"
3,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"[Drama, Crime]"
4,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,"[Animation, Action, Fantasy]"

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        10000 non-null  object
 1   overview     10000 non-null  object
 2   genre_names  10000 non-null  object
dtypes: object(3)
memory usage: 234.5+ KB

In [33]:
df['overview'].eq('').sum()

np.int64(2)

In [34]:
df[df['overview']==""] # There are these two rows with no overview , so I will drop these

       title overview       genre_names
6873  Return           [Drama, Fantasy]
6926     Ret           [Drama, History]

In [35]:
df = df[df['overview']!=""]

In [36]:
df['overview'].str.len().describe() # Minimum characters are 14 and max is upto 987 characters !

count    9998.000000
mean      262.830966
std       127.711917
min        14.000000
25%       159.000000
50%       235.000000
75%       342.750000
max       987.000000
Name: overview, dtype: float64

In [37]:
df.iloc[:,1][0]

"Avatar Aang, the world's last Airbender, learns of an ancient power that could save his culture from extinction. With the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve."

###  So now we have to clean the overview column moving forward:
- First we will conver the entire column text for each row into lowercase.
- We dont have unwanted urls,html tags ,emojis, or short forms judging from the dataset.
- Also since this data is from movies written carefully there is low chance that there are spelling mistakes.
- We are going to remove punctuation marks next.
- We are then going to remove stopwords.
- Then we tokenize the sentences in words
- Then we are gonna use either of stemming or lemmatization.

In [55]:
import re

In [91]:
def preprocess_overview(text):
    # 1. Remove URLs
    text = re.sub(r"https?://\S+", "", text)

    # 2. Remove HTML tags
    text = re.sub(r"<[^>]+>", "", text)

    # 3. Normalize whitespace
    text = re.sub(r"\s+", " ", text)

    # 4. Remove leading/trailing whitespace
    text = text.strip()

    # 5. Lowercase
    text = text.lower()

    return text

df["overview_clean"] = df["overview"].apply(preprocess_overview)

In [94]:
df[["overview", "overview_clean"]].sample(
    3,
    random_state=42
)

,overview,overview_clean
4122,A duplicitous young man finds success in the d...,a duplicitous young man finds success in the d...
4065,"Anne, a brilliant and dedicated advocacy lawye...","anne, a brilliant and dedicated advocacy lawye..."
1731,"Based on the journals of Che Guevara, leader o...","based on the journals of che guevara, leader o..."

In [96]:
# We deliberately left some important punctuation marks that keeps meaning in the sentence .
# Also we are not removing stopwards for now to actual hold current context as it is.

In [126]:
df["tokens"] = df["overview_clean"].apply(word_tokenize) # Store tokens in a new column temporarily

In [134]:
# Currently we have decidede to not remove this stopwords as this also contain important linguistic patterns especially negation which will help in our multi-genre classifier later.

In [164]:
sample_text = df["overview_clean"].sample(
    1,random_state=42
).iloc[0]


tokens = word_tokenize(sample_text)

lemmatizer = WordNetLemmatizer()

lemmatized_tokens = [
    lemmatizer.lemmatize(token)
    for token in tokens
]

for original, lemma in zip(tokens, lemmatized_tokens):
    if original != lemma:
        print(f"{original:20} → {lemma}")

finds                → find
media                → medium
tactics              → tactic
has                  → ha
consequences         → consequence